name: "Netbox"
has_keepalived: false
packages:
  - "unattended-upgrades"
commands:
  - "/opt/netbox/upgrade.sh"
  - "cp /opt/netbox/contrib/gunicorn.py /opt/netbox/gunicorn.py"
  - "cp /opt/netbox/contrib/*.service /etc/systemd/system/"
  - "systemctl daemon-reload"
  - "systemctl enable --now apache2 netbox netbox-rq"
  - "systemctl restart apache2 netbox netbox-rq"
  - "sed -i 's/,noauto//g' /etc/fstab || true"
  - "mount -a || true"
files: []
users: []
mounts: []