name: "ssvp"
has_keepalived: false
packages:
  - "unattended-upgrades"
  - "nfs-common"
  - "mariadb-client"
  - "apache2"
  - "php"
  - "php-common"
commands: [
  "sed -i 's/,noauto//g' /etc/fstab || true",
  "mount -a || true"
]
files: []
users:
  - name: "ryan"
    groups: "sudo"
    shell: "/bin/bash"
    ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDYPhVpxUxaxJbDzPuo9eV6gbon2hhp29U0nxpj+HMg1SiS0L/TMlIybXC79BYSziHilaIOF9luOHUmHp/kmfxvYgFUn4l+hUUaujxMsIVNIbTaz4nQaBuSR4iZHgzj7Q++wUBOk63lmuOetwFeBygqcSMkQyQJ7OSVo6n3bjTHGs7ZKyppRr2IpDhUpA3YWl1nkBKTw/fHElQxMtNk7cjgoOXcJXtBd/7JcBm+SfF65yryOhxYGUWBy32Lmb1zmQ6ATVWk5sDKmlBEotzimvFF6QzBFZy/RNhkj3/h7pv6YF46K5pZFFrpvd8PYs1qrBxzeTZtWuag2tndSJSfd+h4/YgmVdjMkiGH/vwbgrbj5Fsaq6bU5LHLXN0ObtOaTEU712XrTu0zeskUHw/WMT1C1Fr66eRM3vMpXktRnMtomUqrOGdfSTO+b/z85toLDm1jIO8VTOe6yEDQDCpKVtBReDoMItVhlsZKo2aJjuAHaF7bBJ+RWqxdYwv+gd57y48= paranyi@DESKTOP-OQSAT6Q"
mounts:
  - ["nas.jfkhome:/mnt/yes/gitbuilds/ssvp/", "/media/nfs", "nfs", "defaults,nofail", "0", "0"]
  - ["nas.jfkhome:/mnt/yes/gitbuilds/db-server/ssvp/", "/media/db-dumps/ssvp", "nfs", "defaults,nofail", "0", "0"]
  - ["nas.jfkhome:/mnt/yes/gitbuilds/db-server/ssvpu24/", "/media/db-dumps/ssvpu24", "nfs", "defaults,nofail", "0", "0"]
  - ["nas.jfkhome:/mnt/yes/gitbuilds/db-server/ssvpu22/", "/media/db-dumps/ssvpu22", "nfs", "defaults,nofail", "0", "0"]
  - ["nas.jfkhome:/mnt/yes/gitbuilds/db-server/ssvpd13/", "/media/db-dumps/ssvpd13", "nfs", "defaults,nofail", "0", "0"]
